### PR TITLE
[DT][111021972] Pass in channel option to oneautocomplete call

### PR DESCRIPTION
**Pull request by danthamotheram**
Story:
https://www.pivotaltracker.com/story/show/111021972
https://www.pivotaltracker.com/story/show/111016772

Currently, on Rent, when setting up the autocomplete instance with `$el.oneautocomplete({channel: 'foobar'})`, the new channel value does not seem to override the global `window.channel` value at the onesearch.js level.

We want to be able to pass in either a "military" or "college" channel to the autocomplete service, in order to filter the autocomplete suggestion lists for the following seo pages:
http://www.rent.com/housing-near-military-base
http://www.rent.com/off-campus-housing

This PR adds the `options` object into the `extraParams` object so it gets included.

### CODE REVIEW

**Comment by pasha** [comment]
:+1:  just for the reference [AG setup](https://github.com/rentpath/ag/blob/dev/app/assets/javascripts/common/search-light.js#L152)

**Comment by danthamotheram** [comment]
Thanks @pasha . Yes, we do have something similar on Rent too, except that we have not referenced the `window` object with an `exports` variable. (https://github.com/rentpath/rent/blob/dev/app/views/layouts/_js_config.slim#L17)

Just so I understand correctly, re: https://github.com/rentpath/ag/blob/dev/app/assets/javascripts/common/search-light.js#L158 , this `channel` value being passed to oneautocomplete is meant to override the value set on `exports.channel`, correct? 

I ask, because at least on Rent (https://github.com/rentpath/rent/blob/dev/app/assets/javascripts/components/ui/search_bar.coffee#L76), it didn't seem to be working as expected, which was the reason for this fix; I had to manually expose `options.channel` to that `extraParams` object in order for it to override.

**Comment by pasha** [comment]
:+1:

**Comment by danthamotheram** [comment]
Thanks for the chat and clarification, @pasha 

I'll bump the patch version on master now.

**Pull request merged**
